package by.moon.viewbot.enums;

public enum CurrentStep {
    NONE,
    START,
    ADD_QUESTION_FOR_NEW_FREQ_QUESTION,
    ADD_ANSWER_FOR_NEW_FREQ_QUESTION,
    ENTERING_NEW_GREETING,
    ENTERING_NEW_ABOUT_US,
    ENTERING_NEW_CONNECT_WITH_MANAGER,
    ENTERING_NAME_FOR_OUR_PROJECT,
    ENTERING_LINK_FOR_OUR_PROJECT,
    ENTERING_DESCRIPTION_FOR_OUR_PROJECT,
    ENTERING_DESCRIPTION_FOR_REQUEST,
    SENDING_CONTACT_FOR_REQUEST,
    ENTER_USER_MENU_MESSAGE;
}
